### ISSUE TITLE
[BUG] Malformed coverage report

### ISSUE THREAD

**Issue by nabetse28** [tj-actions/coverage-badge-js#98]
I'm using this Github action on my project to generate a badge for coverage. This is my job in the workflow:

```yaml:
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.x"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: "4.4"

      - name: npm install and test
        run: |
          npm install
          npm run test:nyc
          npx prettier --write ./coverage/coverage-final.json
        env:
          CI: true
      - name: Upload test results
        if: success() || failure() # run this step even if previous step failed
        uses: actions/upload-artifact@v2 # upload test results
        with:
          name: test-results
          path: |
            ./mochawesome-report/
            ./coverage

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-js@v1.3
        with:
          report_path: ./coverage/coverage-final.json
```

When I use the action it returns me a "Malformed coverage report". As you can see, I'm using the command `npm prettier` to format my `json` file. I already did a validation of the generated `json` file and it is correct. Can you help me with this??

![image](https://user-images.githubusercontent.com/14103512/123496907-c38ea800-d5e7-11eb-8f34-121e534baab2.png)
